[package]
name = "rusty-nesticle"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.3"
fakeit = "1.3.0"
itertools = "0.13.0"
ratatui = "0.28.1"
unicode-width = "0.2.0"
nesticle-emu = { path = "../nesticle-emu" }
